name: "🐞 Bug Report"
description: "Report a reproducible bug in EncryptBin"
title: "[bug] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! 🙏
        Please fill out the details below so we can reproduce and fix it.

  - type: input
    id: version
    attributes:
      label: "EncryptBin version"
      description: "Which version or commit are you running?"
      placeholder: "e.g. v0.4.4"

  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "How are you running EncryptBin?"
      placeholder: "Docker / Docker Compose / Local Uvicorn / Kubernetes"

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "Step by step, what did you do to trigger the bug?"
      placeholder: |
        1. Start EncryptBin with ...
        2. Paste some text
        3. Click 'Submit'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"

  - type: textarea
    id: actual
    attributes:
      label: "Actual behavior"
      description: "What actually happened?"

  - type: textarea
    id: logs
    attributes:
      label: "Relevant logs or screenshots"
      description: "Paste any error messages, logs, or screenshots"
      render: shell
