---
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Lint
        run: flake8 .

      - name: Format check
        run: black --check .

      - name: Tests + coverage
        run: pytest --cov=. --cov-report=xml --cov-report=term-missing --cov-fail-under=0

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # only needed for private repos
          files: ./coverage.xml
          fail_ci_if_error: false   # ✅ don’t fail build if Codecov is down
