---
name: Screenshots

on:
  pull_request:    # ✅ only run on PRs targeting main
    branches: [ main ]

jobs:
  screenshots:
    runs-on: ubuntu-latest

    services:
      encryptbin:
        build:
          context: .
        ports:
          - 8000:8000
        options: >-
          --health-cmd="curl --fail http://localhost:8000 || exit 1"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=20

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install --with-deps chromium

      - name: Run screenshot script
        run: python scripts/capture.py

      - name: Commit updated screenshots to PR branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[screenshots] update preview images [skip ci]"
          file_pattern: docs/screenshots/*.png
          branch: ${{ github.head_ref }}
